export const nexusRecoveryAbi = [
  { type: "constructor", inputs: [{ name: "_vault", type: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "MAX_HEIRS", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "i_vault", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  {
    type: "function",
    name: "registerRecovery",
    inputs: [
      { name: "heirs", type: "address[]" },
      { name: "splits", type: "uint16[]" },
      { name: "inactivityPeriod", type: "uint256" },
      { name: "gracePeriod", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "deleteRecovery", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "updateHeirs",
    inputs: [
      { name: "heirs", type: "address[]" },
      { name: "splits", type: "uint16[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateInactivityPeriod",
    inputs: [{ name: "period", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateGracePeriod",
    inputs: [{ name: "period", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "depositAVAX", inputs: [], outputs: [], stateMutability: "payable" },
  {
    type: "function",
    name: "withdrawAVAX",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registerToken",
    inputs: [
      { name: "tokenAddress", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deregisterToken",
    inputs: [{ name: "tokenAddress", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "resetTimer", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "initiateClaim",
    inputs: [{ name: "ownerAddress", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "cancelClaim", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "executeClaim",
    inputs: [{ name: "ownerAddress", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getRecoveryConfig",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "heirs", type: "address[]" },
          { name: "splits", type: "uint16[]" },
          { name: "inactivityPeriod", type: "uint256" },
          { name: "gracePeriod", type: "uint256" },
          { name: "lastProofOfLife", type: "uint256" },
          { name: "claimState", type: "uint8" },
          { name: "claimInitiatedAt", type: "uint256" },
          { name: "claimInitiator", type: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getClaimState",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getClaimInitiatedAt",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getHeirs",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [
      { name: "heirs", type: "address[]" },
      { name: "splits", type: "uint16[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRegisteredTokens",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "tokenAddress", type: "address" },
          { name: "amount", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasConfig",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  { type: "error", name: "ConfigAlreadyExists", inputs: [] },
  { type: "error", name: "NoConfigExists", inputs: [] },
  { type: "error", name: "ClaimPending", inputs: [] },
  { type: "error", name: "InvalidSplits", inputs: [] },
  { type: "error", name: "ArrayLengthMismatch", inputs: [] },
  { type: "error", name: "TokenAlreadyRegistered", inputs: [] },
  { type: "error", name: "TokenNotRegistered", inputs: [] },
  { type: "error", name: "ClaimTooEarly", inputs: [] },
  { type: "error", name: "ClaimAlreadyPending", inputs: [] },
  { type: "error", name: "NotAHeir", inputs: [] },
  { type: "error", name: "GracePeriodActive", inputs: [] },
  { type: "error", name: "GracePeriodInActive", inputs: [] },
  { type: "error", name: "NoPendingClaim", inputs: [] },
] as const;
